Portfolio: setup and mobile version skeleton
beyk/mod1-Portfolio pull request #1
Opened 2022-01-07 17:01 UTC by beyk

Implementing portfolio based on Figma template

2022-01-07 17:31 UTC, enkog reviewed
Hi @beyk , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that 

1. **does not have Github flow set up correctly**. 

![Capture](https://user-images.githubusercontent.com/26796167/148581585-e1eb565d-8677-481b-91be-d0ee3de79648.PNG)
The default or base branch should be your `master` branch. I suggest you follow this [guide](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-branches-in-your-repository/changing-the-default-branch) to change the default branch to the `master` branch.

2. **does not have linters set up correctly.**
   I recommend you follow this [guide](https://github.com/microverseinc/linters-config/tree/master/html-css) to set up your linters correctly. This will enable you catch all hidden bugs both locally and remotely.

You should have this; ⬇️ 
![Capture](https://user-images.githubusercontent.com/26796167/148582792-c9808e3d-dac6-4136-a69c-99cbe2329c59.PNG)

Instead of just this ⬇️ 
![Capture](https://user-images.githubusercontent.com/26796167/148583060-5f48d8fa-137e-4783-aa41-907b9857de84.PNG)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-01-08 07:15 UTC, Kingstalux requested changes
Hi @beyk , 

Good job so far!
✔️ You've used the correct Gitflow.
✔️ Your linters are passing.
✔️ Your commit messages are meaningful.
✔️ You've followed the design from the template.
There are some issues that you still need to work on to go to the next project but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>


## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-08 07:15 UTC, Kingstalux commented on index.html
> +        </div>
- [ ] These images here too are meant to be added as background images, and not using the `img`. You can check more about background images [here](https://www.w3schools.com/cssref/pr_background-image.asp).

2022-01-08 07:15 UTC, Kingstalux commented on index.html
> +        </div>
- [ ] This list of icons should use a `ul` tag to group them, and `li` per icon; each icon should also have a link (`a` tag). This is to ensure best semantic practices and it improves the User Interface since these icons take the user to the various accounts.

2022-01-08 07:15 UTC, Kingstalux commented on README.md
> +# Hello Microverse
- [ ] Your README should have as title 'Portfolio' since it's the project you are working on. Do well to correct that.

2022-01-08 07:15 UTC, Kingstalux commented on index.html
> +                Glad to see you!</h1>
- [ ] Your heading is not following the correct font, font color, or font size as the template. Do well to correct that.
- [ ] (OPTIONAL) Also you could add a little margin-top to your navbar for a better User Interface.
- Your design:
![s3](https://user-images.githubusercontent.com/85113567/148635450-e6f33f60-bd00-413b-8607-c28c0d61342b.jpg)
- Figma design:
![s1](https://user-images.githubusercontent.com/85113567/148635460-e1373816-fcb0-464d-9368-2ba2589de3de.jpg)

2022-01-08 09:17 UTC, beyk commented on index.html
> +                Glad to see you!</h1>
Hi @Kingstalux I fixed them, I have to request for reviewing again?

2022-01-08 09:37 UTC, Deepakdanger requested changes
Hi @beyk, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-08 09:37 UTC, Deepakdanger commented on styles/main.css
> +  margin-bottom: 20px;
- [ ] Currently the background images is not showing, as the path you have given is not right. The correct path should be `"../images/bg-shapes.png"` this. Please fix this issue.

2022-01-08 13:40 UTC, julie-ify approved these changes
## Hi @beyk, 

# Highlight
- Good job implementing the required changes from the previous reviewers ✔️  

# Status: Approved ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Approved emoji](https://user-images.githubusercontent.com/81468675/147213535-ab80a883-5bf8-4284-b9ee-d90332328671.gif)

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-08 13:40 UTC, julie-ify commented on index.html
> +                </p>
- [OPTIONAL] 

- [ ] Please consider using the correct width for this `p` as it is so close to the body of your page 😄.

Your page:
<img width="205" alt="Loom_r1xqWTbDTr" src="https://user-images.githubusercontent.com/81468675/148646234-e919c790-48fe-4b28-a507-d0d557ea7a45.png">

2022-01-08 13:57 UTC, merged